name: analysis
on: [push, pull_request]

jobs:
  analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2 # required
      - uses: subosito/flutter-action@v1
        with:
          channel: stable
      - name: analyze
        run: flutter analyze